library(data.table)
library(forecast)
library(lubridate)
library(xts)
library(ggplot2)

daily <-fread("https://www.aavso.org/sites/default/files/solar/NOAAfiles/NOAAdaily.csv")
monthly <- fread("https://www.aavso.org/sites/default/files/solar/NOAAfiles/NOAAmonthly.csv")
#
# Create YYYY-MM-DD Field
daily$Ymd <- as.Date(paste(daily$Year, daily$Month, daily$Day, sep = "-"))
daily$Vote <- ifelse(daily$Ra == 0, 0, 1 )
monthly$Vote <- ifelse(monthly$Ra == 0, 0, 1 )
summary(daily)
sd(daily$Ra)
# cor(daily$Ra)var(daily$Ra)
summary(monthly)
sd(monthly$Ra)
var(monthly$Ra)
# cor(monthly$Ra)
hist(daily$Ra)
boxplot(daily$Ra)
hist(monthly$Ra)
boxplot(monthly$Ra)
daily$ma <-ma(daily$Ra,order=365)
plot(daily$Ymd,daily$Ra)
lines(daily$Ymd,daily$Ra,col="red")
ggplot(data=monthly,aes(Year,Ra)) + geom_smooth() +geom_point()
ggplot(data=daily,aes(Ymd,Ra)) + geom_point() +geom_smooth()
